apiVersion: v1
kind: Service
metadata:
  name: mcp-send-email
  namespace: mcp-servers
  labels:
    app: mcp-send-email
spec:
  selector:
    app: mcp-send-email
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001 
